/*
Copyright isaaguilar.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	tf3v1 "github.com/galleybytes/tf3/pkg/apis/tf3/v1"
	scheme "github.com/galleybytes/tf3/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// TvesGetter has a method to return a TfInterface.
// A group's client should implement this interface.
type TvesGetter interface {
	Tves(namespace string) TfInterface
}

// TfInterface has methods to work with Tf resources.
type TfInterface interface {
	Create(ctx context.Context, tf *tf3v1.Tf, opts metav1.CreateOptions) (*tf3v1.Tf, error)
	Update(ctx context.Context, tf *tf3v1.Tf, opts metav1.UpdateOptions) (*tf3v1.Tf, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, tf *tf3v1.Tf, opts metav1.UpdateOptions) (*tf3v1.Tf, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*tf3v1.Tf, error)
	List(ctx context.Context, opts metav1.ListOptions) (*tf3v1.TfList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *tf3v1.Tf, err error)
	TfExpansion
}

// tves implements TfInterface
type tves struct {
	*gentype.ClientWithList[*tf3v1.Tf, *tf3v1.TfList]
}

// newTves returns a Tves
func newTves(c *Tf3V1Client, namespace string) *tves {
	return &tves{
		gentype.NewClientWithList[*tf3v1.Tf, *tf3v1.TfList](
			"tves",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *tf3v1.Tf { return &tf3v1.Tf{} },
			func() *tf3v1.TfList { return &tf3v1.TfList{} },
		),
	}
}
