kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tf3
subjects:
- kind: ServiceAccount
  name: tf3
  namespace: tf-system
roleRef:
  kind: ClusterRole
  name: tf3
  apiGroup: rbac.authorization.k8s.io