kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: infra3
subjects:
- kind: ServiceAccount
  name: infra3
  namespace: infra3-system
roleRef:
  kind: ClusterRole
  name: infra3
  apiGroup: rbac.authorization.k8s.io