apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf3
  namespace: tf-system
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: tf3
      component: controller
  template:
    metadata:
      labels:
        app: tf3
        component: controller
    spec:
      serviceAccountName: tf3
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      containers:
      - name: tf3
        image: "ghcr.io/galleybytes/tf3:latest"
        imagePullPolicy: IfNotPresent
        command:
        - tf3
        args:
        - --zap-log-level=debug
        - --zap-encoder=console
        env:
        - name: WATCH_NAMESPACE # Leave blank to watch all namespaces
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: OPERATOR_NAME
          value: tf3
        resources:
          limits:
            cpu: 50m
            memory: 128M
          requests:
            cpu: 25m
            memory: 128M
