name: Build Infra3 Container Image

on:
  push:
    tags:
    - 'infra3-*'

jobs:
  infra3-image-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get Release Version
      run: |
        TAG=${GITHUB_REF#refs/tags/}
        VERSION=${TAG#infra3-}
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Build & Push multi-architecture images
      uses: docker/build-push-action@v5
      with:
        context: .
        file: build/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/galleybytes/infrakube:latest
          ghcr.io/galleybytes/infrakube:${{ env.VERSION }}
    
