name: Build tftask Container Images

on:
  push:
    branches:
    - master

jobs:
  tftask-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Build & Push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd task-container-build-tools
        uv run python build-tftask.py

    
